# .github/workflows/DockerBuild.yml
name: Docker image build

on:
  push:
    branches:
      - main  # or master, depending on your repo branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERTOKEN }} | docker login -u "<your-dockerhub-username>" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t <your-dockerhub-username>/<image-name>:latest .
          docker push <harshitcloud>/<image-name>:latest
